// cards.js

const SUITS = ["spades", "hearts", "diamonds", "clubs"];
const VALUES = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const SPECIALS = ["8"];

export const cards = {
    "spades_A":"CAACAgQAAxkBAAN9acfdQllcyvJSsezCNz-4u3MJO2EAAtIcAALZ1wABUY4nboeSXO1POgQ",
"spades_2":"CAACAgQAAxkBAAN-acfdU3OuC5pK19ibB7-sdEIAAZc6AAL9HAACyX34UFFfwZWSFDnmOgQ",
"spades_3":"CAACAgQAAxkBAAN_acfdc5U7BpyjEV45BpATo-oasKcAAiMfAAJh-PlQezLFiwXF2RE6BA",
"spades_4":"CAACAgQAAxkBAAOAacfdghK-6xBbGhh-pa5miMcF4pMAAvIeAAIH6vlQdnJWHJQgvQE6BA",
"spades_5":"CAACAgQAAxkBAAOBacfdkxEwPdENoCUtn3YW21ywJ7gAApogAALv0AFRckSHxGLut9E6BA",
"spades_6":"CAACAgQAAxkBAAOCacfdlPpEaGPWnIJLR4sgdO-MHqgAAnsfAAK7vvhQ-WNYIpYL7e06BA",
"spades_7":"CAACAgQAAxkBAAODacfdluADL_u7Qc2QWB8aw2z_hwEAAuMeAAIs_fhQzPt9OQePd_s6BA",
"spades_8":"CAACAgQAAxkBAAOEacfdmJHSfJ8_Blm_ySRu-ZbpkjgAAnQeAAJ9HPhQvYQIg2kXFFM6BA",
"spades_9":"CAACAgQAAxkBAAOFacfdmrxcq7F5DguKxCo1B3TFFcUAAsciAAI_pPhQvpUqKwNO3vU6BA",
"spades_10":"CAACAgQAAxkBAAOGacfdnljJLPKpN-FHi3N6MbnUYlgAApsfAAKXYgFRd7204kDBWQM6BA",
"spades_J":"CAACAgQAAxkBAAOHacfdoGLwUqf6PHjbSP20eovcjUMAAiMeAAIQMfhQa0bLB30AAdeMOgQ",
"spades_Q":"CAACAgQAAxkBAAOIacfdpN7k0_NtuqizX3_lmTorodwAAnEcAAI-1vhQh1Oj_5YAATsxOgQ",
"spades_K":"CAACAgQAAxkBAAOJacfdrorsSiGE3zlOKAX9kaQO0E0AAgsdAALWAQFRPphNisCTV8A6BA",

    "hearts_A":"CAACAgQAAxkBAANwacfaPXWf2P54EsGof1YN3FLEY48AAoUsAAIJZQFRm9FRjnyOO7M6BA",
"hearts_2":"CAACAgQAAxkBAANxacfaRedwVNZjGP-jLv0s1l-B6tYAAt0fAALf3flQp367J2vK2ic6BA",
"hearts_3":"CAACAgQAAxkBAANyacfaR55gv2ZjAAGlFt98O84RPN_kAAKuHwACJJz5UHP6zeQvjKAMOgQ",
"hearts_4":"CAACAgQAAxkBAANzacfaVaYdnC54XKmJtg7diWIhkEkAAmMdAALyw_lQ-jKRdb2Jfww6BA",
"hearts_5":"CAACAgQAAxkBAAN0acfaW3MOH3bWtcXsos1-rNXwAAEuAAJBHwACX6T4UGYz327MTn8VOgQ",
"hearts_6":"CAACAgQAAxkBAAN1acfaYDUQRf1QEaLplPbf3ViHLRUAAp4cAAJ4GvlQdr7t2vORTh46BA",
"hearts_7":"CAACAgQAAxkBAAN2acfaZPHQC8ax5xpbfj1HYqw-N_kAAlUcAALoQfhQFFS8-WvF_qY6BA",
"hearts_8":"CAACAgQAAxkBAAN3acfaaPgkJ4zJEFo_JIaY1hcrKVgAAikjAALFavhQ0SaD8WIx7nE6BA",
"hearts_9":"CAACAgQAAxkBAAN4acfaaniQzi7KekoDNpfZtmNUMz4AAu4bAAL5A_hQov-PKOo9Qo86BA",
"hearts_10":"CAACAgQAAxkBAAN5acfaay3CD0-1O3Ld0fcPwyy8LvYAAvMfAAKHsgABUT88iVFqh0pvOgQ",
"hearts_J":"CAACAgQAAxkBAAN6acfabiUP0-yPDLZqwL0pG0D7WRUAAigcAAJnjPhQTFNuMuXpxXE6BA",
"hearts_Q":"CAACAgQAAxkBAAN7acfac0FIqQOQyaYUd9URHEgptaQAAi8cAAKnTgABUS-aPxOAvkVnOgQ",
"hearts_K":"CAACAgQAAxkBAAN8acfadP6XdStpH1DzIvvJnvn4OFoAArccAAIREPhQPukzTRkc0U06BA",

    "diamonds_A":"CAACAgQAAxkBAANjacfZgdWO-uuVAAGpayQCgp2HhuWlAAJGHQACVT8AAVEj5Mn99WMEHzoE",
"diamonds_2":"CAACAgQAAxkBAANkacfZkJ8YRHggkRcNAzx5Ha3h4VgAAtocAAK0KgFRz-LBdh_Ov6Q6BA",
"diamonds_3":"CAACAgQAAxkBAANlacfZoZGV232Pjngh0VWndBDfexoAAjEfAAJ00AABUccd04eOkmQvOgQ",
"diamonds_4":"CAACAgQAAxkBAANmacfZowABOiOXINxMRYE19YJzfDkGAAJ7HQAClqH4UMI8vgABQc2xFDoE",
"diamonds_5":"CAACAgQAAxkBAANnacfZqSwtuTrN6Ehg2gIkUAO4-OoAAiweAAITcQABUafKD4m0X57WOgQ",
"diamonds_6":"CAACAgQAAxkBAANoacfZuw0g7hMJAAFIPyKNwO3z8DBvAAJVHwACbuj5UGD6RKIvx64jOgQ",
"diamonds_7":"CAACAgQAAxkBAANpacfZvm66naTqo7sB4JmyzdKYJBgAAlYdAAK3MgFRicFJR0JRF2w6BA",
"diamonds_8":"CAACAgQAAxkBAANqacfZwM_HzS1A-4u5Mor0xy8hMnEAAlYfAAJIk_lQgEEUulD5FFs6BA",
"diamonds_9":"CAACAgQAAxkBAANracfZwYkKLXxmtEyxPZkRpEWbcx8AApQeAAK0BPhQ_TvHnhKK1i06BA",
"diamonds_10":"CAACAgQAAxkBAANUacfYL6qLZvSQwC7KHoS-mvyG1_sAAjclAAJlxvhQZs7q6c5oWXg6BA",
"diamonds_J":"CAACAgQAAxkBAANtacfZyGv9AS1eJY9nbevQSkBArKwAAnweAAIL7flQ3oIU0cHeR386BA",
"diamonds_Q":"CAACAgQAAxkBAANuacfZzBRky8oHOPyXMVQC1sDDLz8AAu0dAAKHiAABUVEE0ybCMVb4OgQ",
"diamonds_K":"CAACAgQAAxkBAANvacfZ0MQiWN9ktAT54sqY9lt1glsAAtohAAImb_lQlQwU1dVTGGs6BA",

    "clubs_A":"CAACAgQAAxkBAANRacfXKHuFR1W9eO2F4rm2aDOlmogAAtMbAAJoAQABUdnOt2uxNFdoOgQ",
"clubs_2":"CAACAgQAAxkBAANSacfXO7s467WHE0wapU9NAAFTyJW5AAKLHAACeroBUUwNiMg1BOr0OgQ",
"clubs_3":"CAACAgQAAxkBAANTacfYCyjvWMrmJEgegErVdmzfDcIAAswaAAKMPPhQp6VqbrIMAAF9OgQ",
"clubs_4":"CAACAgQAAxkBAANZacfYs1afg5a3GHCuO9eM_vKAquAAAiodAAIpZvhQgZQYOUTZD9Q6BA",
"clubs_5":"CAACAgQAAxkBAANaacfYtXQGHhU3y-PzILYt0V2g1koAAuIhAAIuBvlQtZTRacChovs6BA",
"clubs_6":"CAACAgQAAxkBAANbacfYtx1jSlaAmSG70wYW_FMNrX8AAhMeAAJvbwFRHTa0DfwbsLk6BA",
"clubs_7":"CAACAgQAAxkBAANcacfYuq0TO-jrXkwFxvJAYSeoxxQAAjIaAAK8BvlQ1w2z-8FwvsE6BA",
"clubs_8":"CAACAgQAAxkBAANdacfYvJW6YeXggsK7ntpwXqDHGwgAAjYeAAJ6sPhQBs81COo09fk6BA",
"clubs_9":"CAACAgQAAxkBAANeacfYwGhKgT8zA71P6pQAAZHT4wWjAAKWHAACOtsAAVGjKQiRyMfiuDoE",
"clubs_10":"CAACAgQAAxkBAANfacfYw3JRPpZvzaEgMz73pfl7W44AAmscAALsufhQ7JEwA_DLgUQ6BA",
"clubs_J":"CAACAgQAAxkBAANgacfYxnZLrvWw63UzZKQLR7Vw3EUAAsweAAI2l_hQuBu0NUffZ8c6BA",
"clubs_Q":"CAACAgQAAxkBAANhacfYzKHHo7ZjbZl0BkzjzjwaSvsAAsceAAIBhvlQUueBdwwz-Kw6BA",
"clubs_K":"CAACAgQAAxkBAANiacfY0O3GLwUI_xEkUbrgYQ8yWikAAtknAAJ4dwFRAAEF_KpEPiEpOgQ",

// "skip":"CAACAgQAAxkBAAPAacfp_j9E-1vEOKh5Lxvxla2b8gwAAocgAAI79flQyvrsZCnmv6w6BA"
};
export const uniqueIdCards = {
    "spades_A":"AgAD0hwAAtnXAAFR",
"spades_2":"AgAD_RwAAsl9-FA",
"spades_3":"AgADIx8AAmH4-VA",
"spades_4":"AgAD8h4AAgfq-VA",
"spades_5":"AgADmiAAAu_QAVE",
"spades_6":"AgADex8AAru--FA",
"spades_7":"AgAD4x4AAiz9-FA",
"spades_8":"AgADdB4AAn0c-FA",
"spades_9":"AgADxyIAAj-k-FA",
"spades_10":"AgADmx8AApdiAVE",
"spades_J":"AgADIx4AAhAx-FA",
"spades_Q":"AgADcRwAAj7W-FA",
"spades_K":"AgADCx0AAtYBAVE",

"hearts_A":"AgADhSwAAgllAVE",
"hearts_2":"AgAD3R8AAt_d-VA",
"hearts_3":"AgADrh8AAiSc-VA",
"hearts_4":"AgADYx0AAvLD-VA",
"hearts_5":"AgADQR8AAl-k-FA",
"hearts_6":"AgADnhwAAnga-VA",
"hearts_7":"AgADVRwAAuhB-FA",
"hearts_8":"AgADKSMAAsVq-FA",
"hearts_9":"AgAD7hsAAvkD-FA",
"hearts_10":"AgAD8x8AAoeyAAFR",
"hearts_J":"AgADKBwAAmeM-FA",
"hearts_Q":"AgADLxwAAqdOAAFR",
"hearts_K":"AgADtxwAAhEQ-FA",

"diamonds_A":"AgADRh0AAlU_AAFR",
"diamonds_2":"AgAD2hwAArQqAVE",
"diamonds_3":"AgADMR8AAnTQAAFR",
"diamonds_4":"AgADex0AApah-FA",
"diamonds_5":"AgADLB4AAhNxAAFR",
"diamonds_6":"AgADVR8AAm7o-VA",
"diamonds_7":"AgADVh0AArcyAVE",
"diamonds_8":"AgADVh8AAkiT-VA",
"diamonds_9":"AgADlB4AArQE-FA",
"diamonds_10":"AgADNyUAAmXG-FA",
"diamonds_J":"AgADfB4AAgvt-VA",
"diamonds_Q":"AgAD7R0AAoeIAAFR",
"diamonds_K":"AgAD2iEAAiZv-VA",

"clubs_A":"AgAD0xsAAmgBAAFR",
"clubs_2":"AgADixwAAnq6AVE",
"clubs_3":"AgADzBoAAow8-FA",
"clubs_4":"AgADKh0AAilm-FA",
"clubs_5":"AgAD4iEAAi4G-VA",
"clubs_6":"AgADEx4AAm9vAVE",
"clubs_7":"AgADMhoAArwG-VA",
"clubs_8":"AgADNh4AAnqw-FA",
"clubs_9":"AgADlhwAAjrbAAFR",
"clubs_10":"AgADaxwAAuy5-FA",
"clubs_J":"AgADzB4AAjaX-FA",
"clubs_Q":"AgADxx4AAgGG-VA",
"clubs_K":"AgAD2ScAAnh3AVE",

// "skip":"AgADhyAAAjv1-VA",
}